default:
  image: node:latest
  before_script:
    - npm ci --cache .npm --prefer-offline
    - |
      {
        echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=https://registry.npmjs.org/:_authToken=\${CI_JOB_TOKEN}"
        echo "${CI_API_V4_URL#https?}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=\${CI_JOB_TOKEN}"
      } | tee -a .npmrc
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/

workflow:
    rules:
      - if: $CI_COMMIT_BRANCH


variables:
  NPM_TOKEN: ${CI_JOB_TOKEN}

stages: 
  - release


publish:
  stage: release
  script:
     # npm run semantic-release-
    - npm publish --access=public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH